services:
  pypi-viewer:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pypi-viewer.rule=Host(`pypi-inspector.robinjs.dev`)"
      - "traefik.http.routers.pypi-viewer.entrypoints=websecure"
      - "traefik.http.routers.pypi-viewer.tls-certresolver=myresolver"
    build: .
    image: ghcr.io/robin5605/pypi-viewer:latest
    ports:
      - "127.0.0.1:8000:8000"
    tty: true
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: -- interval 30
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=robinjefferson123@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
